---
title: "My template to use flipbook"
subtitle: "A personal template"
author: "Gabriel Santos"
institute: "Pet Sematary"
date: "19-10-2024 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

<!-- Nenhum desses códigos abaixo serão mostrados. Tudo é apenas parte da configuração base dos slides-->

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(fig.width = 6, message = F, warning = F, 
                      comment = "", cache = F)
getwd()
require(tidyverse)
library(flipbookr)
require(palmerpenguins)
# library(MASS) MASS dá conflito. Não entendo o motivo!
require(cowplot)
```

```{r  xaringan-extra-styles, include=FALSE}
xaringanExtra::use_extra_styles(
  hover_code_line = TRUE,         #<<
  mute_unhighlighted_code = FALSE  #<<
)

#xaringanExtra::use_scroll_snap()

```


```{css, eval = TRUE, echo = F}
# DETERMINA O TAMANHO DOS CÓDIGOS
.remark-code{line-height: .8; font-size: 65%}

.remark-slide-scaler {overflow-y: auto;}    #Adiciona barra de rolagem
```

<!--Aqui se encerra o que será considerado como configuração-->


<!--Aqui se encerra o que será considerado como configuração-->


# Now we create the plot

```{r meuplot, echo = F, eval = T, fig.width=7,  fig.align = 'center'}

# Dados aqui é relativo ao pacote penguipalmer
ggplot(data = penguins,
       aes(x = bill_length_mm,
          y = bill_depth_mm,
           group = species)) +
  geom_point(aes(color = species,		 
                 shape = species),
             alpha = 0.8,	# Ajusta a transparência
             size = 3) +
  geom_smooth(method = "lm", se = T, 
              aes(color = species, 
                  fill=species)) +
  scale_color_manual(
    values = c("darkorange",
               "purple","cyan4")) +
  scale_fill_manual(
    values = c("darkorange",
               "purple","cyan4")) +
  labs(title = "Nosso exemplo no ggplot2",
       subtitle = "Tamanho do bico dos penguins Adelie, \nChinstrap e Gentoo Penguins",
       x = "Comprimento do bico(mm)",
       y = "Altura do bico(mm)",
       color = "Espécies de penguins",
       shape = "Espécies de penguins",
       fill = "Espécies de penguins") +
theme_minimal(base_size=18)+
theme(legend.position="bottom")+
facet_grid(.~species,scale="free")
```


---

`r chunk_reveal("meuplot", font_size_code = "70%", title = "#### Now we run flipbook",widths=c(.55,.45))`


<!-- notar que o comando do flipbook é bem diferente do que estou acostumado!
- Primeiro que ele vai solto no slide, sem ser dentro de um chunk de code.
- Segundo é que obrigatoriamente ele precisa vir depois do objeto criado, já nos exemplos iniciais, antes de lançarem o pacote, ele precisava obrigatoriamente vir antes! -->



